name: publish

on:
  push:
    branches: ["main", "dev"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/stg-discord-bot:latest

jobs:

  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run:
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Add secrets
      run: echo ${{ secrets.BOT_TOKEN }} > application.properties

    - name: Build and Publish
      run: |
        docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
  deploy:
    needs: publish
    name: deploy image
    runs-on: ubuntu-latest

    steps:
    - name: install ssh keys
      run: | 
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && sudo docker compose pull && sudo docker compose up -d && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
